version: "2"
services: 
  workspace:
    build:
      context: ./workspace
    tty: true
    depends_on: 
      - mongo
    ports: 
      - "google.com:${APP_PORT}:3000"
    networks: 
      - alc
    command: ["pm2-docker", "server.js"]
  mongo:
    build: 
      args:
        - MONGO_VERSION=${MONGO_VERSION}
      context: ./mongo
    volumes:
      - ${MONGO_DATA}:/data/db
      - ./logs/mongo:/var/log/mongodb
    ports: 
      - ${MONGO_PORT}:27017
    networks:
      - alc

volumes:
  mongo:
    driver: 'local'

networks:
  alc:
    driver: 'bridge'
