version: "2"
services: 
## Workpace container
  workspace:
    build:
      args: 
        - VERSION=${WORKSPACE_IMAGE_VERSION}
        - APPLICATION=${APP_REPO}
      context: ./workspace
    depends_on: 
      - mongo
    ports: 
      - "${APP_PORT}:3000"
    networks: 
      - alc
    command: ["pm2-docker", "start", "pm2.json"]
    restart: on-failure
## Mongo container
  mongo:
    build: 
      args:
        - MONGO_VERSION=${MONGO_VERSION}
      context: ./mongo
    volumes:
      - ${MONGO_DATA}:/data/db
      - ${MONGO_LOGS}:/var/log/mongodb
    ports: 
      - ${MONGO_PORT}:27017
    networks:
      - alc
    restart: on-failure

## Networks
networks:
  alc:
    driver: 'bridge'
