version: "3"
services: 
  app: 
    restart: on-failure
    build: 
      args: 
        - NODE_VERSION=${NODE_VERSION}
        - APP=${APP}
      context: .
    ports: 
      - "3000:3000"
    links:
      - mongo
    depends_on: 
      - mongo
  mongo:
    build: 
      args:
        - MONGO_VERSION=${MONGO_VERSION}
      context: ./mongo
    volumes:
      - ${MONGO_DATA}:/data/db
      - ./logs/mongo:/var/log/mongodb
    ports: 
      - "${MONGO_PORT}:27017"

volumes:
  mongo:
