version: "2"
services: 
  app: 
    restart: on-failure
    build:
      dockerfile: app 
      args: 
        - NODE_VERSION=${NODE_VERSION}
        - APP=${APP}
      context: .
    ports: 
      - ${APP_PORT}:3000
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - alc
  mongo:
    build: 
      args:
        - MONGO_VERSION=${MONGO_VERSION}
      context: ./mongo
    volumes:
      - ${MONGO_DATA}:/data/db
      - ./logs/mongo:/var/log/mongodb
    ports: 
      - ${MONGO_PORT}:27017
    networks:
      - alc

volumes:
  mongo:

networks:
  alc:
    driver: 'bridge'
